/*	This file is used to build the title rental data
base for Dave's Digital Rentals.
	
Created by    : Fernando Arenas and Matt Jones
Date created  : 20/04/09

/*	Building the Customer Table 	*/

create table CUSTOMER (
Customer_ID		number(5) GENERATED AS IDENTITY (START WITH 20001 INCREMENT BY 1),
Fname 			VARCHAR(20) CONSTRAINT CST_FNAME_NN NOT NULL,
LName 			VARCHAR(20) CONSTRAINT CST_LNAME_NN NOT NULL,
Phone			NUMBER(7,4),
Email 			VARCHAR(20) CONSTRAINT CST_EMAIL_NN NOT NULL,
Password		VARCHAR(20) CONSTRAINT CST_PASSWORD_NN NOT NULL,
Address 		VARCHAR(25), 
City			VARCHAR(20),
Postal_Code		VARCHAR(15),
CCType			CHAR(2) 	CONSTRAINT CST_CCTYPE_NN NOT NULL, 
CCNumber		NUMBER(16) 	CONSTRAINT CST_NUMBER_NN NOT NULL,
constraint customer_email_uk unique (email),
constraint customer_postal_code_ck check ((REGEXP_LIKE(postal_code, '[A-Z][0-9][A-Z]-[0-9][A-Z][0-9]'))),
constraint customer_ccnumber_uk unique (ccnumber),
constraint customer_cctype_ck check (cctype IN ('AX', 'MC', 'VS'))
);

INSERT INTO CUSTOMER (FNAME, LNAME, PHONE, EMAIL, PASSWORD, ADDRESS, CITY, POSTAL_CODE, CCTYPE, CCNUMBER)
VALUES ('EDGARDO', 'DULLARD', 726.9455, 'EBENNEDSE@TAOBAO.COM', 'N9RIEE5PG','12 BLUEST_POINT', 'CALGARY', 'T3F-5G2', 'AX', 5602250043566150);

INSERT INTO CUSTOMER (FNAME, LNAME, PHONE, EMAIL, PASSWORD, ADDRESS, CITY, POSTAL_CODE, CCTYPE, CCNUMBER)
VALUES ('ANN', 'STEPHA', 546.6455, 'ADULSON0@TINYPIC.COM', 'VVJVZOYRHGOX','9 MALLARD HILL', 'NEW YORK', 'T4T-5H2', 'MC', 358804485401234);

INSERT INTO CUSTOMER (FNAME, LNAME, PHONE, EMAIL, PASSWORD, ADDRESS, CITY, POSTAL_CODE, CCTYPE, CCNUMBER)
VALUES ('STEPHA', 'DULSON', 221.5455, 'SFIDELUS1@ZDNET.COM', 'JEFNOVMLLGB','0 TENNYSON PARK', 'REGINA', 'H6R-5K8', 'VS', 3545644854010760);

INSERT INTO CUSTOMER (FNAME, LNAME, PHONE, EMAIL, PASSWORD, ADDRESS, CITY, POSTAL_CODE, CCTYPE, CCNUMBER)
VALUES ('PATRICE', 'BOSMA', 913.9753, 'PBOSMA2@BAIDU.COM', 'TVVVUGZK9DUR','39535 SPOHN AVENUE', 'HOPE', 'U5M-6H6', 'AX', 3584567854010760);

INSERT INTO CUSTOMER (FNAME, LNAME, PHONE, EMAIL, PASSWORD, ADDRESS, CITY, POSTAL_CODE, CCTYPE, CCNUMBER)
VALUES ('YEVETTE', 'PERFECT', 573.1235, 'YPERFECT3@YALE.EDU', 'XUPH6EOK1M','61 NORTHVIEW PARKWAY', 'NO HOPE', 'I7T-8K8', 'MC', 3588044987410760);
