REM Report2

/*	This file is used to build a report to show all 
the movies released in the last 30 days base on Dave's Digital Rentals.
	
Created by    : Fernando Arenas and Matt Jones
Date created  : 20/04/09

/*	Report: Shows and movies coming out in the last 30 days 	*/

set echo off
set feedback off
set linesize 45
set pagesize 45
set underline on

ttitle 	center 'Movies Released In The Last 30 Days' skip 3 

btitle left 'Generated by: ' format A10 SQL.USER skip 2 -
	center 'For internal use only' left _date right 'Page: ' format 9 SQL.PNO;

column "Title" format A30 heading "Title";
column "Release Date" format A13 heading "Release Date";

Break on "Release Date" on report;

compute count label "Total amount" of "Release Date" on report;

spool "C:\cprg250\projectf\spool\Report_2.txt";

select 	initcap(show_title) "Title", release_date "Release Date"
from 	title
where 	release_date >=  	(sysdate - 30)
and 	release_date <= 	sysdate;

spool off;
ttitle off;
btitle off;
repheader off;
repfooter off;
clear columns;
clear compute;
clear break;