REM Report 3
/*	This file is used to build a report to show all 
the movies a customer put on their wishlist on Dave's Digital Rentals.
	
Created by    : Fernando Arenas and Matt Jones
Date created  : 20/04/09

/*	Report: Customers Favorite Movies 	*/


set echo off
set feedback off
set linesize 51
set pagesize 45
set underline on

spool "C:\cprg250\project\spool\Report_3.txt"; 

column "Favorite Titles" format A30 heading "Favorite|Titles";
column "Customer Name" format A20 heading "Customer|Name";

ttitle 	center 'Customers Favorite Movies' skip 3

btitle left 'Generated by: ' format A10 SQL.USER skip 2 -
	center 'For internal use only' left _date right 'Page: ' format 9 SQL.PNO;

Break on "Customer Name" skip 2 on report;

compute count label "Total Favorites" on "Customer Name" of "Favorite Titles";

select 	initcap(fname || ' ' || lname) "Customer Name", initcap(show_title) "Favorite Titles"
from customer 	join wishlist_item using (customer_id)
				join title using (title_id)
group by show_title, fname, lname
order by lname, fname;


spool off;
ttitle off;
btitle off;
repheader off;
repfooter off;
clear columns;
clear compute;
clear break;